/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/dutch_ship_medium_1k.gltf -t -r public
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    dutch_ship_medium_rigging: THREE.Mesh;
    dutch_ship_medium_hull: THREE.Mesh;
    dutch_ship_medium_sails: THREE.Mesh;
  };
  materials: {
    dutch_ship_medium_rigging: THREE.MeshStandardMaterial;
    dutch_ship_medium_hull: THREE.MeshStandardMaterial;
    dutch_ship_medium_sails: THREE.MeshStandardMaterial;
  };
};

export default function DutchShip(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/dutch_ship_medium_1k.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.dutch_ship_medium_rigging.geometry}
        material={materials.dutch_ship_medium_rigging}
      />
      <mesh
        geometry={nodes.dutch_ship_medium_hull.geometry}
        material={materials.dutch_ship_medium_hull}
      />
      <mesh
        geometry={nodes.dutch_ship_medium_sails.geometry}
        material={materials.dutch_ship_medium_sails}
      />
    </group>
  );
}

useGLTF.preload("/models/dutch_ship_medium_1k.gltf");
